Add RWR plus card extension page
brunojppb/austria-expat-tips pull request #4
Opened 2019-10-23 20:05 UTC by mmoura-nc

2019-10-23 20:18 UTC, Tschis requested changes

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +# What I need to extend my Visa?
typo: "What do I need"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +To initiate the process of extending the RWR plus card you need to proceed to the [MA 35](https://www.wien.gv.at/kontakte/ma35/) office that covers the district your are currently living. It is recom
typos: 
- "**you are** currently living **in**"
- "your current visa expires" or "your current visa expiration date"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +You will need to present the follow documentation, to assure that you are in order with their imigration laws:
typo: "**following** documentation"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +    3 lastest payment slips (yours, if you are currenly working)
typo: "latest"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +- Meldezettel (if you move since your last application)
typo: "moved"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> + If your RWR card plus it based on your patner Visa, and this person it the money provider, it is import to also have the copies of his/her documents:
typos:
- "is based"
- "partner"
- "is the money provider"
- "it is important"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> + - 3 lastest payment slips
typo: "latest"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +After you present the documentation to the MA35 representant, they will scan your finger digitals and hand you a payment bill for the new card that currently costs 160,00.
Suggestion: add date to "currently", also add "euros" or "€"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +¹If everything goes well, it takes around 30 to 40 days for new RWR plus card be ready. You need to comeback to the same office with the pay bill receipt and some valid Id documentation (Passaport or
typos: 
- "for the new", 
- "card to be ready"
- "come back"
- "paid bill"
- "passport"
- "current visa"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +²The [KSV1870](https://www.ksv.at/en) is a report that confirms to the authorities or your landlord that you’ll be financially reliable. It is valid for 3 months and currently cost about 30,00.
typo: "costs"

Also, add "euros" or "€"

2019-10-23 20:18 UTC, Tschis commented on common/extend-visa.md
> +The Application Form is not currently available on the Internet, you will most probable find in the MA 35 office.
typo: 
- "most probably"
- "find it in"

2019-10-23 20:33 UTC, Tschis commented on common/extend-visa.md
> + If your RWR card plus it based on your patner Visa, and this person it the money provider, it is import to also have the copies of his/her documents:
> typos:
> 
> * "is based"
> * "partner"
> * "is the money provider"
> * "it is important"

My bad:  "partner's"

2019-10-23 20:33 UTC, Tschis commented
LGTM

2019-10-23 21:24 UTC, brunojppb commented on common/extend-visa.md
> +After you present the documentation to the MA35 representant, they will scan your finger digitals and hand you a payment bill for the new card that currently (10/2019) costs 160,00 €.
I believe you meant `fingerprints`

2019-10-24 07:05 UTC, mmoura-nc commented on common/extend-visa.md
> +After you present the documentation to the MA35 representant, they will scan your finger digitals and hand you a payment bill for the new card that currently (10/2019) costs 160,00 €.
Yes, thank you.

2019-10-24 07:15 UTC, merged